version: 2.1

executors:
  docker-executor:
    docker:
      - image: node:20.14.0-alpine
    working_directory: ~/app

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Clean npm cache (Fix for "could not determine executable to run")
          command: npm cache clean --force && rm -rf node_modules package-lock.json && npm install

      - run:
          name: Install Expo CLI
          command: npm install -g expo-cli

      - run:
          name: Install EAS CLI
          command: npm install -g eas-cli

      - run:
          name: Install Missing Expo Dependencies
          command: npm install expo-system-ui

      - run:
          name: Install Missing Expo Dependencies
          command: npx jest --passWithNoTests
          
      - run:
          name: Install Git (Fix for "git command not found")
          command: apk add --no-cache git

      - run:
          name: Build APK
          command: |
            npx expo prebuild
            npx eas build --platform android --profile preview --non-interactive

      - store_artifacts:
          path: /home/circleci/app/build
          destination: apk-files

workflows:
  version: 2
  build:
    jobs:
      - build
